language: python
python:
  - "3.5"
# command to install dependencies
install:
  - pip install -r build/requirements.txt
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below